export const FETCH_LIST_NEWS_POSTS = 'FETCH_LIST_NEWS_POSTS'
export const FETCH_LIST_NEWS_POSTS_SUCCESS = 'FETCH_LIST_NEWS_POSTS_SUCCESS'
export const FETCH_LIST_POSTS_FAILED = 'FETCH_LIST_POSTS_FAILED'
export const MESSAGE_NEW_POSTS = 'Bài viết mới nhất'